### ISSUE TITLE
[8.2-fpm-apache] Can't add imagick

### ISSUE THREAD

**Issue by Thijmen** [shinsenter/php#43]
Hi there,

Using this Docker image for quite some time, thank you for your efforts.

Today, I tried to create a Docker image with the following base-image:

```
ARG PHP_VERSION=8.2
ARG PHP_VARIATION=fpm-apache

FROM shinsenter/php:${PHP_VERSION}-${PHP_VARIATION} AS base


ARG BUILD_TAG

# Set the environment variable based on the tag
ENV BUILD_VERSION=$BUILD_TAG


ENV WEBHOME="/app"
ENV APACHE_DOCUMENT_ROOT="/web"
ENV TZ="Europe/Amsterdam"
ENV PHP_POST_MAX_SIZE="200M"
ENV PHP_UPLOAD_MAX_FILE_SIZE="200M"


RUN phpaddmod imagick
```

Above image is unable to build for me;

```
12.30 Installing curl
12.31 Reading package lists...
12.64 Building dependency tree...
12.72 Reading state information...
12.82 curl is already the newest version (7.88.1-10+deb12u5).
12.82 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
12.82 Installing PHP modules:  imagick
13.53 Installing PHP modules:  imagick
13.55 install-php-extensions v.2.1.81
13.55 #StandWithUkraine
13.58 /usr/local/aliases/php: line 2: cd: /app: No such file or directory
------
Dockerfile:20
--------------------
  18 |     
  19 |     
  20 | >>> RUN phpaddmod imagick
--------------------
ERROR: failed to solve: process "/bin/sh -c phpaddmod imagick" did not complete successfully: exit code: 1
```

Any tips as of why this might happening? Thanks in advance!

**Comment by Thijmen** [comment]
`a2enconf` is also not available anymore unfortunately. Is there a changelog where I can find these changes?

**Comment by shinsenter** [comment]
Hello @Thijmen

Thank you for using and providing feedback on our docker images.

Regarding your issue, we have pushed a bug-fix and hope new docker images with the fix will be updated soon within the next 5-6 hours. We look forward to continue receiving your feedback on the bug-fix release.

We are gradually releasing new docker images built on top of the official php docker images, to ensure PHP applications and modules receive the latest updates from upstream. As such, when using these new docker images, there will be changes inside the containers as the base OS will change (debian or alpine instead of Ubuntu like in the old version), and we are working to minimize major changes when you use them compared to the previous docker images.

We suggest migrating your Dockerfile like below to better optimize for the new docker images.

```Dockerfile
ARG PHP_VERSION=8.2
ARG PHP_VARIATION=fpm-apache

FROM shinsenter/php:${PHP_VERSION}-${PHP_VARIATION} AS base

ARG BUILD_TAG

# Set the environment variable based on the tag
ENV BUILD_VERSION=$BUILD_TAG

ENV APP_PATH="/app"
ENV DOCUMENT_ROOT="/web"
ENV TZ="Europe/Amsterdam"
ENV PHP_POST_MAX_SIZE="200M"
ENV PHP_UPLOAD_MAX_FILE_SIZE="200M"

RUN phpaddmod imagick

// and instructions for building the final stage will be here
// ...
```

We are updating the documentation for the new docker images, though not yet fully complete but please feel free to take a look.
https://github.com/shinsenter/php/blob/5.x/README.md

One more thing to consider when you use multi-staged builds is that when you copy all files from the build stage to a new image (say copy to a scratch image), necessary environment variables in the original docker image and metadata from the official php docker images will be lost, and you need to copy them over to the final stage. To minimize this work, I suggest you can use my docker-squash utility to reduce the effort for you.
https://github.com/shinsenter/docker-squash

Then, you just need to focus on creating the Dockerfile and run the following command to copy over all files as well as metadata from your Dockerfile to a brand new image:

```bash
./docker-squash.sh /path/to/my-project/Dockerfile -t my-project:latest
```

```Dockerfile
ARG PHP_VERSION=8.2
ARG PHP_VARIATION=fpm-apache

FROM shinsenter/php:${PHP_VERSION}-${PHP_VARIATION}

ARG BUILD_TAG

# Set the environment variable based on the tag
ENV BUILD_VERSION=$BUILD_TAG

ENV APP_PATH="/app"
ENV DOCUMENT_ROOT="/web"
ENV TZ="Europe/Amsterdam"
ENV PHP_POST_MAX_SIZE="200M"
ENV PHP_UPLOAD_MAX_FILE_SIZE="200M"

RUN phpaddmod imagick
```

**Comment by Thijmen** [comment]
Hey @shinsenter thanks for your fast reply! I fully understand that you try to stay up to date with upstream and that involves changes.

I got a question; previously, the ENV variables were being copied over I guess - is that a change related to the change that you've described above?  We'll try to change our CI to include docker-squash as well.

**Comment by shinsenter** [comment]
@Thijmen 

I apologize if I may have misunderstood your meaning when you mentioned multi-stage builds.

> I create a "base" image first (multi-staged build) and then in the last step, COPY the files to it.
It seems you just create a base image from my docker image, then copy your application source code into that base image. If doing so, it completely retains the environment variables and metadata of the original image.

In my thinking, you would build a base image called the build stage, then copy all files from the build stage to a final stage using a scratch image (Docker has described [some examples here](https://docs.docker.com/build/building/multi-stage/)). After copying files to a new scratch image, all environment variables and meta data from the origin image will be lost.

**Comment by Thijmen** [comment]
Gotcha! I did some more digging into how the docker image works now and was able to alter my Dockerfile so it works now. Thanks for your support and keep up the good work, love the repo! ❤️
