### ISSUE TITLE
Getting authz_core:error permission error

### ISSUE THREAD

**Issue by baldhadhaval08** [shinsenter/php#47]
Hello,

I was using `shinsenter/phpfpm-apache:php7.4` in my drupal project and it stop working now.

I'm getting
`[Mon Feb 05 12:48:27.763371 2024] [authz_core:error] [pid 1888:tid 140016370005760] [client 122.169.51.168:35532] AH01630: client denied by server configuration: /site/drupal/
`

![image](https://github.com/shinsenter/php/assets/36040948/b13c80d7-65a9-4b21-ab0f-e7efbefed5a1)

**Comment by shinsenter** [comment]
@baldhadhaval08 

I apologize for any disruption this may cause. We are rolling out updated docker images based on the official php images. Rest assured we have taken steps to minimize the impact of this change on your existing setup.

We are using different docker image tags to maintain the old docker image versions. All old docker images have been published with `*-deprecated` tag names. However, we will no longer provide any update for the old docker images.
https://hub.docker.com/r/shinsenter/php/tags?page=1&name=-deprecated

If you don't mind sharing with me the dockerfile or docker-compose.yml for your project, I think I may be able to assist you in migrating your docker container to work with the new docker images.

Please let me know if you have any other questions or concerns - we're committed to making this a seamless process.

Best regards.

**Comment by baldhadhaval08** [comment]
@shinsenter 

Yes I can able to run it with deprecated images. You can find docker-composer and Dockerfile in attachement


[docker-compose.txt](https://github.com/shinsenter/php/files/14168211/docker-compose.txt)
[Dockerfile.txt](https://github.com/shinsenter/php/files/14168212/Dockerfile.txt)

**Comment by shinsenter** [comment]
@baldhadhaval08 

It's good to know your project has no issues using the `shinsenter/php:7.4-fpm-apache-deprecated` docker images. I think for now it's a way to feel comfortable using your current Dockerfiles and docker-compose.yml.

If you plan on using my new docker images, there are some notes that the base OS has changed from Ubuntu to Debian or Alpine (since these new images are built on official docker images). I don't think there will be any issues when you need to install additional extensions with the `phpaddmod` utility.
https://github.com/shinsenter/php/blob/5.x/README.md#adding-php-extensions

Also, some environment variables (such as application directory, document root directory, etc.) have been re-documented here. 
https://github.com/shinsenter/php/blob/5.x/README.md#application-directory

I don't think it will take too much time for you to make the changes, for example:

```Dockerfile
ENV WEBHOME="/site/drupal"
ENV APACHE_DOCUMENT_ROOT="/web"

ENV PHP_MAX_EXECUTION_TIME="300"
ENV PHPFPM_SOCK_PATH="/var/run/php/php-fpm.sock"
```

should be changed to:

```Dockerfile
ENV APP_PATH="/site/drupal"
ENV DOCUMENT_ROOT="/web"

ENV PHP_LISTEN="/run/php-fpm.sock"
ENV PHP_MAX_EXECUTION_TIME="300"
```

I am planning to publish docker images for Drupal, and I will soon update it, which will help make your Dockerfile more simpler.

Please let me know if you have any other questions or concerns.

Best regards.
