### ISSUE TITLE
PHP & Pecl state

### ISSUE THREAD

**Issue by Bsd-us** [shinsenter/php#62]
Hey,

As a beginner I wanted to use your image for a project where I need to install mongodb via pecl, though I couldn't make it work because of the state of php and pecl

At first, just using pecl command was problematic :
```
PHP Warning:  Failed to set memory limit to 0 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
ERROR: The default config file is not a valid config file or is corrupted.
```

I found someone on internet saying I should rm /usr/local/etc/pear.conf, and it did make it pass the warning but trying:
```
root@66b184571134:/var/www/html# pecl install mongodb
PHP Warning:  Failed to set memory limit to 0 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
Invalid channel name "pecl.php.net"

invalid package name/package file "mongodb"
install failed
```

Even though I'm still getting this weird memory error I think the important thing here is about the channel name, I couldn't find anything about it, and it is repeated in a lot of the commands I'm trying
Can someone help ?

**Comment by shinsenter** [comment]
Hello @Bsd-us , thank you for your feedback

I will review it and put out an updated version soon to improve on this issue.

Regards.

**Comment by shinsenter** [comment]
Hey @Bsd-us

Could you please provide me with a Dockerfile or a minimal setup so that I can reproduce and verify the issue you are experiencing?

By the way, could you also provide me with the tag of the Docker image you are having the issue with?

**Comment by shinsenter** [comment]
@Bsd-us 

Thank you for providing the setup to reproduce the issue with the Docker image you are using. I will try to provide a temporary fix. Since the Docker images will be fully updated in about 6-8 hours, please wait and try again.

In addition, if you want to install PHP modules for your Docker image, I recommend [using the `phpaddmod` utility to install PHP](https://github.com/shinsenter/php?tab=readme-ov-file#adding-php-extensions) modules ***during the Docker image build phase*** instead of installing modules in a running container.

### Example
You can use a Dockerfile like the following example to add the mongodb module:

```Dockerfile
FROM shinsenter/symfony:latest

RUN phpaddmod mongodb
```

### Explanation:

- The `FROM` instruction specifies the base Docker image to use. In this case, we are using the `shinsenter/symfony:latest` image.
- The `RUN` instruction runs a command inside the container during the image build process. In this case, we are using `phpaddmod mongodb` to install the mongodb PHP module.

You can add additional PHP modules to the `RUN` instruction as needed.

I hope this helps!

**Comment by Bsd-us** [comment]
Thank you for your fast answers, with that fix it works perfectly now ! 
What I was missing was phpaddmod, even though I saw it in your documentation, seing the required pecl install command needed to install mongodb I thought it wouldn't work, as it seemed very specific.
Also don't worry for my bad practice, I was installing inside the running container only to know what steps I was going to need to include in my Dockerfile 
Thank you so much again !
