### ISSUE TITLE
PHPFPM-Apache - s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by 6rendon** [shinsenter/php#64]
Able to run locally but not in a container environment such as AWS ECS. When I do, I get error:

**s6-overlay-suexec: fatal: can only run as pid 1**

This is the Dockerfile contents:
```
FROM shinsenter/phpfpm-apache:php8.1

# Set environment variables
ENV PHP_PM_MAX_CHILDREN=100
ENV PHP_PM_START_SERVERS=20
ENV PHP_PM_MIN_SPARE_SERVERS=10
ENV PHP_PM_MAX_SPARE_SERVERS=35
ENV PHP_PM_MAX_REQUESTS=1000
ENV PHP_UPLOAD_MAX_FILESIZE=200M
ENV APP_PATH=/var/www/foo
ENV DOCUMENT_ROOT=/var/www/foo/html

# Update and install additional packages
RUN phpaddmod \
    mcrypt \
    memcache \
    pgsql \
    rdkafka \
    soap \
    stomp \
    xdebug \
    xsl

# Set the working directory
WORKDIR /var/www/foo

# Copy application files
COPY . .

# Copy Apache vhosts configuration
COPY docker/apache/vhosts.conf.template /etc/apache2/sites-available/vhosts.conf

# Enable the site configuration
RUN a2ensite vhosts.conf

# Copy and unzip server.zip
COPY docker/foo/server.zip /tmp/server.zip
RUN unzip /tmp/server.zip -d /var/www/conf/ \
    && rm /tmp/server.zip

# Run Composer install commands
RUN composer install --no-dev --no-scripts --prefer-dist -o -d /var/www/foo \
    && composer install --no-dev --no-scripts --prefer-dist -o -d /var/www/foo/includes/classes/Azure/ExternalAPI

# Modify PHP settings and create necessary directories
RUN sed -i \
    -e 's/error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT/error_reporting = E_ALL \& ~E_DEPRECATED \& ~E_STRICT \& ~E_WARNING \& ~E_NOTICE/g' \
    "$PHP_INI_DIR/php.ini" \
    && mkdir -p /mnt/file_archive/{logs,dx,dx_archive,storage,cached} \
    && mkdir -p /var/www/conf \
    && mkdir -p /var/www/foo/html/foo/css/cached \
    && chown -R www-data:www-data /var/www

# Expose necessary ports
EXPOSE 80
```

I also tried the following suggestion

```
CMD [ "exec", "/init" ]
```

**Comment by shinsenter** [comment]
I also suspect that there might be a possibility that [ECS Exec](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html) is enabled on your container host. ECS Exec wants to own pid 1, which is causing conflicts with s6-overlay. [This issue is currently being discussed on GitHub](https://github.com/just-containers/s6-overlay/issues/559) and there is no definitive solution yet. 

I will continue to follow this issue and update you as soon as a patch is available for s6-overlay.

In the meantime, you can try the following workaround: disabling ECS Exec will prevent it from taking over pid 1 and allow s6-overlay to function properly. However, this will also mean that you will not be able to use ECS Exec to connect to your containers.

I hope this information is helpful. Please let me know if you have any other questions.

Best regards,

**Comment by 6rendon** [comment]
Hello,

**Comment by shinsenter** [comment]
@6rendon

Sure, you can email me at shin@shin.company. I'm happy to help when I can, but please note that I have limited time for free technical support.

To understand your issue better, please provide a detailed explanation. This will help me see if I can address it quickly. If the issue is beyond my expertise or needs more extensive attention, I'll direct you to some helpful resources.

Thank you for your understanding.
